--- 
- 
  connection: local
  gather_facts: false
  hosts: local
  name: "Stage instance"
  tasks: 
    - 
      local_action: "ec2 instance_type=$instance_type image=$image region=$region group=default count=1 wait=true assign_public_ip=true"
      name: "Launch instance"
      register: ec2
    - 
      local_action: "add_host hostname=${item.public_ip} groupname=launched"
      name: "Itemised host group addition"
      with_items: "${ec2.instances}"
  user: root
  vars: 
    image: ami-debb97b6
    instance_type: t2.micro
    key_name: mykey
    region: us-east-1
    wait: true
